Correct files

diff --git a/ch1/find_path_progs/inpath b/ch1/find_path_progs/inpath
--- a/ch1/find_path_progs/inpath
+++ b/ch1/find_path_progs/inpath
@@ -38,16 +38,18 @@ checkForCmdInPath()
 	fi
 }
 
-if [ $# -ne 1 ] ; then
-	echo "Usage: $0 command" >&2
-	exit 1
-fi
+# ONLY NEEDED FOR TESTING THE SCRIPT
 
-checkForCmdInPath "$1"
-case $? in
-	0 ) echo "$1 found in PATH"			;;
-	1 ) echo "$1 not found or not executable" 	;;
-	2 ) echo "$1 not found in PATH"			;;
-esac
-
-exit 0
+# if [ $# -ne 1 ] ; then
+# 	echo "Usage: $0 command" >&2
+# 	exit 1
+# fi
+#
+# checkForCmdInPath "$1"
+# case $? in
+# 	0 ) echo "$1 found in PATH"			;;
+# 	1 ) echo "$1 not found or not executable" 	;;
+# 	2 ) echo "$1 not found in PATH"			;;
+# esac
+#
+# exit 0
